server:
  port: 8080
#  servlet:
#    session:
#      cookie:
#        # 需要更换存放sessionId的cookie名字，否则认证服务和客户端的sessionId会相互覆盖
#        name: JSESSIONID-2

spring:
  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          # 客户端应用名
          myClient:
            client-id: client_lww
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/myClient
            scope: openid, profile, read, all
            # 授权服务提供平台名
            provider: lww-sas
        provider:
          lww-sas:
            #授权地址   client.szile.com为配置的授权服务  避免和客户端同域名Session冲突
            authorization-uri: http://oauth.local.server:9000/oauth2/authorize
            # 访问令牌地址
            token-uri: http://oauth.local.server:9000/oauth2/token
            # 用于验证jwt签名  的 oauth2授权服务器的公钥集合
            jwk-set-uri: http://oauth.local.server:9000/oauth2/jwks

